### ISSUE TITLE
Build fails for aosp_xqau51-userdebug and aosp_xqau52-userdebug

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/device-sony-pdx201#8] opened 2020-06-22 09:44 UTC
Here is my command history of initializing repo, I've followed instructions from link in README.md
```
mkdir aosp10-build
cd aosp10-build/
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r37
cd cd .repo/repo/repo
cd cd .repo/repo/
cd .repo/repo/
ls
cp repo /home/hospitality/bin/
cd ..
ls
la
cd .repo/
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests/
git checkout android-10.0.0_r37
cd ..
repo sync
./repo_update.sh
. build/envsetup.sh
lunch
make -j4
```
and here how it it fails:
```
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=aosp_xqau51
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a73
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a73
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-119-generic-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ3A.200605.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/seine vendor/qcom/opensource/core-utils
============================================
[ 99% 12377/12378] finishing build rules ...
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module 'NexusLauncherOutOfProcTests'
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module 'NexusLauncherDebug'
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module 'NexusLauncherTests'
platform_testing/build/tasks/tests/platform_test_list.mk: warning: platform_tests: Unknown installed file for module 'LauncherRotationStressTest'
platform_testing/build/tasks/tests/platform_test_list.mk: warning: platform_tests: Unknown installed file for module 'PlatformScenarioTests'
11:37:33 Build configuration changed: "aosp_xqau52-userdebug" -> "aosp_xqau51-userdebug", forcing installclean
FAILED: ninja: 'kernel/sony/msm-4.14/common-kernel/kernel-dtb-pdx201', needed by 'out/target/product/pdx201/kernel', missing and no known rule to make it
11:37:36 ninja failed with: exit status 1

#### failed to build some targets (04:33 (mm:ss)) ####
```
There is no kernel-dtb-pdx201 file in freshly initialized repo, there are others though so maybe I can reuse these (make a symlink or a copy)?

**Comment by MarijnS95** [comment] 2020-06-22 09:49
Please use the `bug_tracker` to report issues, and fill in the template.

In this particular case no kernel prebuilt exists because the device is still somewhat in development (though we are very, very close). Please manually the kernel for now.

**Comment by AngryGami** [comment] 2020-06-22 10:20
I've never done this myself before and instructions from https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices looks outdated and crippled, e.g.:
```
Prepare repository...
rm –r device/sony/common-kernel
```
there is no such path in repo, I assume it is about `kernel/sony/msm-4.14/common-kernel`, though deleting this folder didn't help, it doesnt even try to build kernel, just fails.
Manual build instructions are also looks strange e.g.:
```
export CROSS_COMPILE=/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-
```
this line is trimmed. List of devices is lacking anything older than Xperia X. 
So it looks like this:
![image](https://user-images.githubusercontent.com/2470910/85276685-821e6680-b482-11ea-8234-d0201e68f1d6.png)

**Comment by MarijnS95** [comment] 2020-06-22 10:23
> So it looks like this:

Then all I can say is: wait for the device to be finished properly, at which point prebuilts become available.

**Comment by AngryGami** [comment] 2020-06-22 10:25
There is no way I can get more comprehensive instructions of how to build kernel from somewhere else?

**Comment by ix5** [comment] 2020-06-22 15:23
This is a documentation failure.

Go into kernel/sony/msm-4.14/common-kernel, look for the `build-kernel-clang.sh` script, add `seine` into the platform array and `pdx201` into `SEINE`, also add the dtbo flag. Basically, make a duplicate of kumano.

---

But, considering you didn't arrive at this solution yourself, I can only agree with Marijn that you should wait until kernel prebuilts are available. You will run into lots of frustrating issues otherwise that you will not be able to solve with your current skill level, as we are in the early bringup phase.

**Comment by AngryGami** [comment] 2020-06-22 15:36
@ix5  thanks, I've did exactly that :)
https://github.com/sonyxperiadev/bug_tracker/issues/604

**Closed** 2020-06-23 06:31 UTC
